#!/bin/bash

# Adresse I2C du capteur BMP280
BMP280_ADDR=0x76
BMP280_ID_REG=0xD0
EXPECTED_ID_BMP280=0x58

if i2cget -f -y 2 $BMP280_ADDR $BMP280_ID_REG >/dev/null 2>&1; then
	ID=$(i2cget -f -y 2 $BMP280_ADDR $BMP280_ID_REG)

	if [ "$ID" == "$EXPECTED_ID_BMP280" ]; then
 		echo "Capteur BMP280 trouve a l'adresse $BMP280_ADDR. ID correct: $ID"
	else
 		echo "Capteur BMP280 trouve a l'adresse $BMP280_ADDR, mais l'ID est incorrect: $ID"
	fi
else
	echo "Capteur BMP280 non detecte a l'adresse $BMP280_ADDR"
fi
