#!/bin/bash

# Adresse I2C du capteur MPU-9250
MPU9250_ADDR=0x68
MPU9250_ID_REG=0x75
EXPECTED_ID_MPU9250=0x71

if i2cget -f -y 2 $MPU9250_ADDR $MPU9250_ID_REG >/dev/null 2>&1; then
	ID=$(i2cget -f -y 2 $MPU9250_ADDR $MPU9250_ID_REG)

	if [ "$ID" == "$EXPECTED_ID_MPU9250" ]; then
 		echo "Capteur MPU-9250 trouve a l'adresse $MPU9250_ADDR. ID correct: $ID"
	else
 		echo "Capteur MPU-9250 trouve a l'adresse $MPU9250_ADDR, mais l'ID est incorrect: $ID"
	fi
else
	echo "Capteur MPU-9250 non detecte a l'adresse $MPU9250_ADDR"
fi
